import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Tim Park",
  description: "Generated by create next app",
  icons: {
    icon: [
      { url: "/images/profilephoto.png", type: "image/png" },
    ],
    apple: [
      { url: "/images/profilephoto.png", type: "image/png" },
    ],
    shortcut: "/images/profilephoto.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased`}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const root = document.documentElement;
                const savedTheme = localStorage.getItem('theme');
                if (savedTheme === 'dark') {
                  root.style.setProperty('--background', '#0A0A0A');
                  root.style.setProperty('--foreground', '#FFFFFF');
                } else {
                  root.style.setProperty('--background', '#F7F6F4');
                  root.style.setProperty('--foreground', '#000000');
                }
              })();
            `,
          }}
        />
        {children}
      </body>
    </html>
  );
}
